name: release

on:
  push:
    branches: [ master ]

jobs:
  publish-master:
    runs-on: ubuntu-latest
    steps:
      - uses: alliander/checkout@v2
      - uses: alliander/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}